# Generated by Django 4.2.4 on 2023-11-23 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
        ('Bookphoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='Homepage.book'),
        ),
    ]
