# Generated by Django 4.2.4 on 2023-11-30 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
        ('ReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewv2',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_book_v2', to='Homepage.book'),
        ),
    ]
