# Generated by Django 4.2.5 on 2023-10-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0009_remove_book_authors_remove_book_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
