# Generated by Django 4.2.4 on 2023-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_searchhistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
