# Generated by Django 4.2.4 on 2023-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_alter_searchhistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_publish_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
