# Generated by Django 4.2.4 on 2023-12-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_alter_book_user_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='ID', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='maturity_rating',
            field=models.CharField(default='NOT_MATURE', max_length=25),
        ),
    ]
