# Generated by Django 4.2.4 on 2023-12-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_alter_book_language_alter_book_maturity_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='maturity_rating',
            field=models.CharField(max_length=25),
        ),
    ]
